import Link from "next/link";
import Faq from "@/components/Faq";
import Stat from "@/components/Stat";
import CreatorPostCard, { type CreatorPost } from "@/components/CreatorPostCard";
import RevealOnScroll from "@/components/RevealOnScroll";
import HeroScene from "@/components/three/HeroScene";
import { hasSessionCookie } from "@/lib/session";

const SAMPLE_POSTS: CreatorPost[] = [
  {
    name: "Alex Rivera",
    title: "Creator · B2B & AI · 34K followers",
    hook: "How AI changed the way our sales team prioritizes leads.",
    impressions: "42.8K",
    clicks: "312",
    leads: "18",
  },
  {
    name: "Jordan Kim",
    title: "Creator · Sales & AI · 12K followers",
    hook: "I run my entire prospecting workflow through an AI agent. Here's how.",
    impressions: "9K",
    clicks: "100",
    leads: "50",
  },
  {
    name: "Morgan Diaz",
    title: "Sales Leader · B2B · 40K followers",
    hook: "Most sales teams waste 80% of their time on the wrong leads.",
    impressions: "20K",
    clicks: "350",
    leads: "80",
  },
  {
    name: "Sam Okafor",
    title: "Content Creator · B2B · 34K followers",
    hook: "My 30-day LinkedIn content system, the exact playbook.",
    impressions: "100K",
    clicks: "1,600",
    leads: "320",
  },
];

const HOW_IT_WORKS = [
  {
    step: "01",
    title: "Find creators your buyers trust",
    body: "Compare vetted B2B voices by audience fit, not just follower count.",
  },
  {
    step: "02",
    title: "Build a campaign brief in minutes",
    body: "Set objectives, key messages and creator guidelines with AI assistance.",
  },
  {
    step: "03",
    title: "Manage every collaboration",
    body: "Track drafts, scheduling and go-live status from one dashboard.",
  },
  {
    step: "04",
    title: "Track reach, clicks and leads",
    body: "Attribute pipeline back to the exact post that drove it.",
  },
  {
    step: "05",
    title: "Pay creators without the admin",
    body: "Contracts, invoices and payouts handled automatically.",
  },
];

const FAQ_ITEMS = [
  {
    question: "What is this platform?",
    answer:
      "A B2B LinkedIn creator marketplace: companies discover and book vetted creators for sponsored LinkedIn campaigns at a fixed price per post set by the creator.",
  },
  {
    question: "How are creators vetted?",
    answer:
      "Creators are reviewed for audience quality and topical fit before they can list on the marketplace, not just follower count.",
  },
  {
    question: "Which networks are supported?",
    answer: "LinkedIn is the primary channel today, with support for other networks on the roadmap.",
  },
  {
    question: "How does per-post pricing work?",
    answer: "Each creator sets their own fixed rate per post; you see the price up front before booking.",
  },
  {
    question: "How does attribution work?",
    answer: "Every campaign gets unique tracking links so clicks, leads and pipeline map back to the exact post.",
  },
  {
    question: "Do you handle creator payouts?",
    answer: "Yes — payouts, contracts and invoicing are handled automatically once a post goes live.",
  },
];

export default async function HomePage() {
  const ctaHref = (await hasSessionCookie()) ? "/dashboard" : "/register";

  return (
    <div>
      <section className="relative overflow-hidden bg-gradient-to-b from-[#c5ebfd] to-[#fcfcfb] px-6 pb-24 pt-16 text-center">
        <HeroScene />
        <div className="relative z-10 mx-auto max-w-3xl">
          <span className="inline-flex items-center gap-2 rounded-full bg-white/70 px-4 py-1.5 text-xs font-medium text-[#3a3b40]">
            Where B2B brands work with creators
          </span>
          <h1 className="mt-6 text-5xl font-semibold leading-tight tracking-tight text-[#17181c] sm:text-6xl">
            The B2B LinkedIn
            <br />
            Creator Marketplace.
          </h1>
          <p className="mx-auto mt-6 max-w-xl text-lg text-[#3a3b40]">
            Find the creators your buyers already trust, launch campaigns in days, and
            track the clicks, leads and pipeline generated by every post.
          </p>
          <div className="mt-8 flex flex-wrap items-center justify-center gap-4">
            <Link
              href={ctaHref}
              className="rounded-full bg-[#17181c] px-6 py-3 text-sm font-semibold text-white hover:opacity-90"
            >
              Launch a campaign →
            </Link>
            <Link href="#how-it-works" className="text-sm font-semibold text-[#17181c] underline">
              See how it works →
            </Link>
          </div>
          <p className="mt-10 text-xs uppercase tracking-wide text-[#5a5b60]">
            Trusted by modern B2B teams
          </p>
        </div>
      </section>

      <RevealOnScroll className="mx-auto max-w-4xl px-6 py-16 text-center">
        <p className="text-xs font-semibold uppercase tracking-wide text-[#8a8b90]">Case study</p>
        <blockquote className="mt-4 text-2xl font-medium text-[#17181c]">
          “We manage a significant influence budget every year. For B2B, this marketplace
          simply makes our life easier.”
        </blockquote>
        <p className="mt-4 text-sm text-[#3a3b40]">CEO, Independent Influence Agency</p>
      </RevealOnScroll>

      <section id="how-it-works" className="bg-white px-6 py-20">
        <div className="mx-auto max-w-5xl">
          <RevealOnScroll className="max-w-2xl">
            <p className="text-xs font-semibold uppercase tracking-wide text-[#8a8b90]">
              One platform, from brief to results
            </p>
            <h2 className="mt-3 text-3xl font-semibold text-[#17181c] sm:text-4xl">
              Run creator campaigns from one place.
            </h2>
            <p className="mt-3 text-[#3a3b40]">
              Find the right voices, launch faster, and connect every post to measurable
              business results.
            </p>
          </RevealOnScroll>

          <RevealOnScroll
            stagger={0.1}
            className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-5"
          >
            {HOW_IT_WORKS.map((item) => (
              <div key={item.step} className="rounded-2xl border border-black/5 p-5">
                <span className="text-xs font-semibold text-[#8a8b90]">{item.step}</span>
                <p className="mt-3 font-semibold text-[#17181c]">{item.title}</p>
                <p className="mt-2 text-sm text-[#3a3b40]">{item.body}</p>
              </div>
            ))}
          </RevealOnScroll>
        </div>
      </section>

      <section className="px-6 py-20">
        <RevealOnScroll stagger={0.1} className="mx-auto grid max-w-5xl gap-12 sm:grid-cols-4">
          <Stat value="5M+" label="Impressions generated" />
          <Stat value="30K+" label="Leads generated" />
          <Stat value="2,000+" label="Creators on the platform" />
          <Stat value="5K+" label="Posts published" />
        </RevealOnScroll>
      </section>

      <section className="bg-white px-6 py-20">
        <div className="mx-auto max-w-5xl">
          <h2 className="text-3xl font-semibold text-[#17181c]">Real posts from real creators.</h2>
          <RevealOnScroll stagger={0.08} className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
            {SAMPLE_POSTS.map((post) => (
              <CreatorPostCard key={post.name} post={post} />
            ))}
          </RevealOnScroll>
        </div>
      </section>

      <section id="pricing" className="px-6 py-20">
        <RevealOnScroll className="mx-auto max-w-5xl text-center">
          <p className="text-xs font-semibold uppercase tracking-wide text-[#8a8b90]">
            Get started
          </p>
          <h2 className="mt-3 text-3xl font-semibold text-[#17181c] sm:text-4xl">
            Start free. Pay per post when you&apos;re ready.
          </h2>
        </RevealOnScroll>

        <RevealOnScroll stagger={0.1} className="mx-auto mt-12 grid max-w-4xl gap-6 sm:grid-cols-2">
          <div className="rounded-3xl border border-black/5 bg-white p-8">
            <p className="text-xs font-semibold uppercase tracking-wide text-[#8a8b90]">
              Self-serve
            </p>
            <h3 className="mt-2 text-xl font-semibold text-[#17181c]">Run it yourself.</h3>
            <p className="mt-2 text-sm text-[#3a3b40]">
              For teams that want the infrastructure to run creator campaigns in-house.
            </p>
            <p className="mt-6 text-3xl font-semibold text-[#17181c]">
              €0 <span className="text-base font-normal text-[#8a8b90]">/ month</span>
            </p>
            <ul className="mt-6 space-y-2 text-sm text-[#3a3b40]">
              <li>Creator marketplace access</li>
              <li>AI-powered brief creation</li>
              <li>Track clicks, companies and pipeline</li>
              <li>Automatic creator payouts</li>
            </ul>
            <Link
              href={ctaHref}
              className="mt-8 block rounded-full bg-[#17181c] px-5 py-2.5 text-center text-sm font-semibold text-white hover:opacity-90"
            >
              Start for free
            </Link>
          </div>

          <div className="rounded-3xl border border-black/5 bg-white p-8">
            <p className="text-xs font-semibold uppercase tracking-wide text-[#8a8b90]">
              Managed campaigns
            </p>
            <h3 className="mt-2 text-xl font-semibold text-[#17181c]">Get your time back.</h3>
            <p className="mt-2 text-sm text-[#3a3b40]">
              For teams that want the campaigns operated end to end.
            </p>
            <p className="mt-6 text-3xl font-semibold text-[#17181c]">Custom quote</p>
            <ul className="mt-6 space-y-2 text-sm text-[#3a3b40]">
              <li>Campaign strategy and positioning</li>
              <li>Creator sourcing and coordination</li>
              <li>Brief creation and campaign launch</li>
              <li>Reporting and optimisation</li>
            </ul>
            <Link
              href="/agencies"
              className="mt-8 block rounded-full border border-black/10 px-5 py-2.5 text-center text-sm font-semibold text-[#17181c] hover:bg-black/5"
            >
              Book a campaign call
            </Link>
          </div>
        </RevealOnScroll>
      </section>

      <section id="faq" className="bg-white px-6 py-20">
        <RevealOnScroll className="mx-auto max-w-3xl">
          <p className="text-xs font-semibold uppercase tracking-wide text-[#8a8b90]">
            Frequently asked questions
          </p>
          <h2 className="mt-3 text-3xl font-semibold text-[#17181c]">
            Everything you need to know.
          </h2>
          <div className="mt-8">
            <Faq items={FAQ_ITEMS} />
          </div>
        </RevealOnScroll>
      </section>

      <RevealOnScroll className="px-6 py-24 text-center">
        <p className="text-xs font-semibold uppercase tracking-wide text-[#8a8b90]">
          Ready to launch?
        </p>
        <h2 className="mx-auto mt-3 max-w-2xl text-3xl font-semibold text-[#17181c] sm:text-4xl">
          Your next creator campaign starts here.
        </h2>
        <div className="mt-8 flex flex-wrap items-center justify-center gap-4">
          <Link
            href={ctaHref}
            className="rounded-full bg-[#17181c] px-6 py-3 text-sm font-semibold text-white hover:opacity-90"
          >
            Start for free
          </Link>
          <Link
            href="/agencies"
            className="rounded-full border border-black/10 px-6 py-3 text-sm font-semibold text-[#17181c] hover:bg-black/5"
          >
            Book a campaign call
          </Link>
        </div>
      </RevealOnScroll>
    </div>
  );
}
